src/crypto/internal/boring/boring.go
LDFLAGS in our fork should container `-ldl` however upstream recently
added `-lpthread` because their boringcrypto .syso requires it now.
This got mangled in the rebase, this patch adds back the correct linker
argument.
Fixes #3
=> crypto/boring: Fix LDFLAGS

src/crypto/internal/boring/ecdsa.go
Because of the PublicKeyECDSA (pub) finalizer, any time pub.key is passed to cgo, that call must be followed by a call to runtime.KeepAlive, to make sure pub is not collected (and finalized) before the call returns.
VerifyECDSA does call runtime.KeepAlive, but that call will be deleted if the compiler can prove that h is always 0, leaving _goboringcrypto_internal_ECDSA_verify call vulnerable at garbage collector mercy.
The fix is easy, just add a runtime.KeepAlice call to the h == crypto.Hash(0) branch.
PD. We (Go team at Microsoft) found this bug when porting the OpenSSL bindings in here to our own repo, located at https://github.com/microsoft/go-crypto-openssl. To be specific, the test that caught the use-after-free error was [TestECDSASignAndVerify](https://github.com/microsoft/go-crypt …
=> crypto/boring: fix use-after-free bug in VerifyECDSA

.ci/Dockerfile, .github/workflows/build-image.yml
This integrates a Docker image building into the GitHub actions, so the generated image can be used in our CI workflow for testing.
The workflow definition is based on:
https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages
**Note that this workflow uses manual trigger (`workflow_dispatch`), which only works in the default branch on GitHub, so this PR is really intended for `main`.**
Signed-off-by: Daiki Ueno <dueno@redhat.com>
=> .github/workflows: add workflow to build Docker image

src/crypto/internal/boring/aes.go, src/crypto/internal/boring/boring.go, src/crypto/internal/boring/ecdsa.go, src/crypto/internal/boring/hmac.go, src/crypto/internal/boring/notboring.go, src/crypto/internal/boring/rand.go, src/crypto/internal/boring/rsa.go, src/crypto/internal/boring/sha.go
The previous ports had this change, though it was apparently missed in the 1.18 rebase.
Signed-off-by: Daiki Ueno <dueno@redhat.com>
=> crypto/boring: Remove restriction on build architecture

.ci/Dockerfile
The openssl-devel package needs to be manually installed, as it is not
part of the golang build dependencies in Fedora.
Signed-off-by: Daiki Ueno <dueno@redhat.com>
=> .github/workflows/build-image.yml: pull in openssl-devel

scripts/setup-initial-patch.sh
Adds some more changes which cause the TLS boring tests to pass.
After this change, running the script, applying the patches and
then running `GOLANG_FIPS=1 go test -run Boring ./...` all tests
will pass.
=> Fix initial patch setup script

scripts/setup-initial-patch.sh
Not sure how this got by my testing, but when
the testConfigTemplate function is added to the
Go source file we should use a bash append (">>")
instead of the alternative which will replace the
entire contents of the file with only the function,
causing compilation to fail.
=> Fix initial setup script (pt 2)

patches/000-initial-setup.patch
A few new changes included in the initial setup patch combined with https://github.com/golang-fips/openssl-fips/pull/10 allow new branches setup with the setup script to execute the tests without any further modification.
=> Update initial setup patch with new modifications

patches/000-initial-setup.patch
This patch enables TLS 1.3 even in FIPS mode.  To make the implementation FIPS compliant, it also delegates ECDH and HKDF operations to the FIPS certified library (openssl) through the openssl-fips package.
Fixes: #33
Fixes: #34 
Signed-off-by: Daiki Ueno <dueno@redhat.com>
=> Update initial patch to support TLS 1.3

patches/000-initial-setup.patch
Add cgo build tag to crypto/internal/backend/openssl.go.
Fixes #48.
=> add cgo build tag to crypto/internal/backend/openssl.go

patches/000-initial-setup.patch
This API was removed during the transition to 1.19. This patch adds it back. It was originally requested because the FIPS lab insisted that hashing / signing (or verifying) happen in a single openssl call.
=> Add HashSign/HashVerify

patches/000-initial-setup.patch
Currently, makeClientHello() only selects FIPS ciphers when running in boring mode.  It should also use FIPS ciphers when using fipstls.Force().
Fixes golang-fips/openssl-fips#23
=> [crypto/tls] fix makeClientHello with fipstls.Force()

patches/000-initial-setup.patch
Upstream Go limits public keys in certificates to
2048 or 3072 bits.  This change adds support for
public keys of size 4096.
=> [crypto/x509] Allow 4096 bit keys in boring mode

patches/000-initial-setup.patch
handshake_client.go no longer requires an import
on crypto/internal/boring.  Also TestBoringCertAlgs
needs to accept 4096 bit keys.
I'm not sure why my previous testing didn't catch these
issues but here's a follow-up PR to fix them.
=> remove boring import in handshake_client.go and fix tls tests

patches/000-initial-setup.patch
There are a few restrictions enforced when OpenSSL 3.0 is used under FIPS mode, that are incompatible with the Go tests, namely:
- For creating signature, encrypting, and decrypting, RSA key size must be equal to or longer than 2048 bits
- For verifying signature, RSA key size must be equal to or longer than 1024 bits
- PKCS#1 v1.5 is not supported for encryption and decryption (signing and verification are still allowed)
This either skips the relevant tests or increases key size used for testing.
This should fix the test failures in `crypto` tests as mentioned in golang-fips/openssl-fips#25.
=> Make crypto tests work with OpenSSL 3.0 under FIPS

scripts/setup-go-submodule.sh
Currently, the setup scripts only support targeting branches of upstream Go.  This can cause previously working versions of the setup to break out from under us whenever those branches are updated by the Go
community.
This commit adjusts the setup scripts to support targeting tags and commits, allowing users to target upstream Go refs which are known to be fully compatible with the golang-fips setup process.
=> Allow setup using tags and commits

config/versions.json, scripts/create-secondary-patch.sh, scripts/setup-go-submodule.sh, scripts/versions.go
Currently the scripts target the latest commit on a given branch. This is because the original intent was to set up a source branch once and then continually rebase upstream Go on top of it.  However, this is not the way the workflow has played out so far.  For Go 1.19+, we're currently distributing as scripts and patches that generate a golang-fips tree on top of an upstream Go ref.
This commit introduces a `versions.json` file with a mapping between repo versions and git refs for golang/go, golang-fips/go, and golang-fips/openssl-fips.  The setup scripts now read from `versions.json` when selecting the default git refs, allowing us to standardize dependencies to known working versions where a given commit of golang-fips/go will behave consistently.  A side effect is that the argument to …
=> Pin dependency versions

scripts/full-initialize-repo.sh
Most of the time when generating the FIPS patches, I also want to apply them back to the Go tree.  This commit adds a new script which applies the patches back to the tree after running setup-initial-patch.sh.
=> Add full-generate-repo script

scripts/full-initialize-repo.sh
Most of the time when generating the FIPS patches, I also want to apply them back to the Go tree.  This commit adds a new script which applies the patches back to the tree after running setup-initial-patch.sh.
=> [Go 1.19 Backport] Add full-generate-repo script

patches/001-initial-openssl-for-fips.patch
Include a copy of the generated 001-initial-openssl-for-fips.patch to allow offline builds of the toolchain without having to download the openssl-fips module.
=> Include 001-initial-openssl-for-fips.patch

config/versions.json, patches/000-initial-setup.patch, patches/001-initial-openssl-for-fips.patch, scripts/configure-crypto-tests.sh
Variations in behavior between OpenSSL versions and distributions often causes the crypto test suite to be incompatible when porting between linux distros. This PR introduces a TestConfig backend for more easily configuring the crypto test suite in FIPS mode.
To configure which algorithms and key types are supported by OpenSSL, adjustments can now be made to the paramaters in `crypto/internal/backend/boringtest/config.go`  A script is also added for convenience.
This PR also disables TLSv1.3 for OpenSSL versions older than v1.1.1, which fixes crashes when using those versions.  This was batched in because there was a lot of overlap in the implementation work.
=> Add Crypto TestConfig and fix TLSv1.3 Crashes

patches/002-strict-fips-runtime-detection.patch, scripts/crypto-test.sh
This pull request hardens strict fips mode by forbidding 1024 bit key generation outside of test cases.  To use 1024 bit key generation for testing in strict fips mode, users must explicitly call the newly implemented `GenerateKeyNotBoring` interface, which panics when executed outside of a testing context.
This PR also implements crypto-test.sh which tests Go in both normal fips and strict fips modes for convienience.
=> [Go 1.19] Restrict key generation and add test script

src/crypto/internal/boring/boring.go, src/crypto/internal/boring/strict_fips.go
This check can not happen before the openssl
backend is initialized.
=> Fix OpenSSL Runtime Check

.github/workflows/gating.yml, src/net/http/h2_bundle.go
Backport of https://github.com/golang/net/commit/b225e7ca6dde1ef5a5ae5ce922861bda011cfabd
Also enable mainline gating.
=> [Go 1.15] h2-bundle: fix CVE-2023-39325

src/net/http/internal/chunked.go, src/net/http/internal/chunked_test.go
Backport of patch which fixes CVE 2023-39326 to Go1.15
https://go-review.googlesource.com/c/go/+/547355
=> Backport of patch for CVE 2023-39326 to Go1.15

src/net/http/internal/chunked.go, src/net/http/internal/chunked_test.go
backport of patch that fixes CVE 2023-39326 to Go1.16 
https://go-review.googlesource.com/c/go/+/547355
=> Backport of patch for CVE 2023-39326 to Go1.16

src/net/http/internal/chunked.go, src/net/http/internal/chunked_test.go
Backport of fix for CVE 2023-39326 to Go1.17 
https://go-review.googlesource.com/c/go/+/547355
=> Backport of patch for CVE 2023-39326 to Go1.17

src/net/http/internal/chunked.go, src/net/http/internal/chunked_test.go
Backport of patch https://go-review.googlesource.com/c/go/+/547355 to Go1.18-openssl-fips branch
=> backport of patch for CVE 2023-39326 to Go1.18

patches/007-fix-CVE-2023-45285.patch
Backporting the following fix to CVE 2023-45285 
The two lines in the .txt file needed to be changed to work with the older style of commands in TestScripts/ testing engine
https://go-review.googlesource.com/c/go/+/540257/3/src/cmd/go/testdata/script/mod_insecure_issue63845.txt
=> Backport of fix to CVE 2023-45285 for Go1.19

patches/015-fix-linkage.patch
go binary (tested with v1.21.7 on Oracle Linux) seems to be missing vendored openssl patches. 
```
$ go tool nm $(which go) | grep -i openssl-fips
$ 
```
The above command returns nothing. Derek suggested that https://go-review.googlesource.com/c/go/+/454836 might be the reason for this. 
I wanted to try a smaller change-set and so i think setting toolenv to empty string should work. I tried a make.bash and it worked and linkage is fine post that. 
fixes https://github.com/golang-fips/go/issues/186
First time submitting a PR here, so please let me know if any changes are required.
=> fix linkage issue in RH builds

patches/004-skip-pkcs-test.patch
TestOverlongMessagePKCS1v15 tests that an error is returned on an invalid message. We can safely skip the test, as the constraint doesn't apply when using OpenSSL versions with implicit rejection in RSA PKCS#1 v1.5, which would return a random message instead of an error.
=> Skip broken PKCS overlong message test

patches/003-fix-linkage.patch
https://github.com/golang-fips/go/pull/190 fixed a linkage issue in RH builds.
This PR aims to backport that fix to the go1.21-fips-release branch
=> backport of linkage fix to v1.21

patches/015-fix-crashdumpallthreads.patch, patches/016-fix-crashdumpallthreads.patch
- Backport change https://go-review.googlesource.com/c/go/+/554615 to Go1.22. This fix increases sleep time
long enough to see that SIGQUIT is passed on to all threads and avoids CrashDumpAllThreads failure on s390x
- Fixes: GT-243
=> Backport change https://go-review.googlesource.com/c/go/+/554615 to Go1.22

patches/015-add-hash-sign-verify.patch
The last patch restoring these functions modified the signature to match the new one exposed by openssl.HashSignECDSA and also the stdlib SignANS1/VerifyASN1 functions. This breaks consumers relying on the original API, so this patch restores that while using the new API under the hood.
=> patches: restore signature of HashSign/HashVerify

config/versions.json, patches/001-initial-openssl-for-fips.patch
Fixes https://github.com/golang-fips/go/issues/187
=> config: update openssl backend

config/versions.json
rebase to pick latest Go1.22 release 
contains fix for CVE-2024-24791 and Go issue https://go.dev/issue/67555.
=> Rebase to Go1.22.5 to fix CVE-2024-24791

patches/006-skip-pkcs-test.patch
=> Added skip pkcs test patch to avoid CI error on ubi8 for PR 213

config/versions.json, patches/001-initial-openssl-for-fips.patch
Include commit golang-fips/openssl#143 and supporting changes that removes usage of EC_KEY* functions to enforce FIPS restrictions
=> Rebase to include changes related to EC_KEY* functions that support FIPS restrictions 

patches/007-fix-CVE-2024-24790.patch
taken from https://go-review.googlesource.com/c/go/+/590316
fixes CVE-2024-24790
=> Backport of fix for CVE-2024-24790 to Go1.20

patches/010-fix-CVE-2024-24790.patch
Backport of fix for CVE 2024-24790 to Go1.19
https://go-review.googlesource.com/c/go/+/590315
=> Backport of fix for CVE 2024-24790 to Go1.19

patches/011-fix-CVE-2024-24791.patch
- Backport of fix for CVE-2024-24791 to Go1.19
- https://go-review.googlesource.com/c/go/+/595096
=> Backport of fix for CVE-2024-24791 to Go1.19

config/versions.json
Rebase to Go1.21.13 (technically 1.21.12 contains fix for CVE 2024-24791) but since we have a latest release, rebase to that
=> Rebase to Go1.21.13

patches/018-fix-std-crypto.patch
We shouldn't depend on OpenSSL in non-FIPS mode, as it precludes binaries from running in any environment without OpenSSL.  This commit moves the FIPS mode check to the beginning of init() and avoids initializing OpenSSL when we know Go standard crypto will be used.
=> Only load OpenSSL when in FIPS mode.

patches/018-fix-std-crypto.patch
This commit avoids loading openssl whenever GOLANG_FIPS is not 1. Previously only an unset variable would cause the library load to be skipped, but users may also expect to be able to set eg. GOLANG_FIPS=0 in environments without openssl.
=> Only load openssl if fips equals "1"

src/crypto/rsa/pkcs1v15_test.go, src/encoding/gob/decode.go, src/encoding/gob/decoder.go, src/encoding/gob/gobencdec_test.go
Cherry-pick two commits to Go 1.16 to fix encoding/gob issue. Please do not squash when merging.
=> Go1.16 encoding/gob fixes

patches/001-initial-openssl-for-fips.patch
The initial openssl patch was not updated in the previous update to the openssl bindings.
=> Update initial openssl patch

patches/022-openssl-negative-tests.patch
This patch adds assertions around expected failures when using OpenSSL in FIPS mode.
=> Add negative tests for openssl

config/versions.json, patches/023-crypto-tls-fix-config-time.patch
And backport https://github.com/golang/go/commit/3417000c69bc89c173cfafcf3f2a06a408b32880
=> Update to Go 1.23.4

patches/009-TLS-test-fix.patch
carried over changes from https://go-review.googlesource.com/c/go/+/640237 to Go1.21
=> Backport of fix for crypto/TLS tests to update config.Time

scripts/setup-go-submodule.sh
Some organizations use a fork of the Go repository rather than the upstream repo; those organizations can set the environment variable `GOLANG_REPO` to point to that repo for the fetch instead.
=> Allow fetching from a fork of the Go repo

patches/012-fix_expired_certificates.patch
Issue link: golang/go#71077
Upstream patch: https://go-review.googlesource.com/c/go/+/639655
=> [Backport] fix Config.Time in tests using expired certificates

patches/012-fix_expired_certificates.patch
There was an extra comma causing a build failure.
=> [go1.19] Fix expired certificates patch

patches/011-remove-parallel-test-everything.patch
This method, while good for performance, is interfering with OpenSSL and Go interactions by accidentally hiding errors. This is due to likely to the goroutine being preempted during CGO calls. There is a series of circumstances that leads to the OpenSSL thread local error state being overwritten causing us to lose the error, and thus fail the test.
=> [go1.21] Remove the call to parallelize TestEverything

patches/014-remove-parallel-runs-of-test-everything-rsa.patch
This method, while good for performance, is interfering with OpenSSL and Go interactions by accidentally hiding errors. This is due to likely to the goroutine being preempted during CGO calls. There is a series of circumstances that leads to the OpenSSL thread local error state being overwritten causing us to lose the error, and thus fail the test.
=> [go1.20] Remove the call to parallelize TestEverything

patches/013-fix-usleep-s390x.patch
Backport fix to correct usleep asm implementation on s390x
https://go-review.googlesource.com/c/go/+/648915
=> Backport fix to correct usleep asm implementation on s390x to Go1.21

patches/020-fix-usleep-s390x.patch
Backport fix to correct usleep asm implementation on s390x for Go1.22
https://go-review.googlesource.com/c/go/+/648915
=> Backport fix to correct usleep asm implementation on s390x for Go1.22

patches/014-reject-newlines-in-chunked-lines.patch
https://go-review.googlesource.com/c/go/+/657216
Fixes: CVE-2025-22871
=> net/http: reject newlines in chunk-size lines (backport to 1.21)

src/net/http/internal/chunked.go, src/net/http/internal/chunked_test.go, src/net/http/serve_test.go
https://go-review.googlesource.com/c/go/+/657216
Fixes: CVE-2025-22871
=> net/http: reject newlines in chunk-size lines (backport to 1.17)

patches/fips.patch, scripts/crypto-test.sh
This was previously left unimplemented and would panic if invoked. We didn't catch this because we only run a subset of the TLS tests in FIPS mode. This patch adds the test case which would have caught this into our test script and fixes the panic with an implementation of HKDF label expanding.
Fixes #297
=> Implement HKDF for TLS

.github/workflows/gating.yml
Also remove c8s, which we don't support anymore.
Depends on https://github.com/golang-fips/release/pull/17/files
=> Go 1.24: Add ubi10, c10s targets to gating

.github/workflows/gating.yml
Also remove c8s, which we don't support anymore.
Depends on https://github.com/golang-fips/release/pull/17/files
=> Go 1.23: Add ubi10, c10s targets to gating

.github/workflows/gating.yml
Also remove c8s, which we don't support anymore.
=> [Go 1.21] Add ubi10, c10s targets to gating

patches/003-fix-hkdf-extract.patch
The latest OpenSSL in c9s/c10s requires nil salt to be passed as a hash length buffer of zeros. This commit is a backport of https://github.com/golang-fips/openssl/pull/276/commits/0ec829d1b13eeb598f2de7b3278fe7138d24c1e6
=> [Go 1.25] Fix HKDF-Extract
